version: '3.8'

services:
  frontend:
    build: ./Front
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    volumes:
      - ./Front/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  backend:
    build: ./Back
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=176.123.179.219
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=(9IeuwbxaDwckDue
      - DB_NAME=enactusticket
      - SERVER_PORT=8080
      - ADMIN_LOGIN=Aidana
      - ADMIN_PASSWORD=admin
      - ALLOWED_ORIGINS=https://vencera.tech,http://176.123.178.135:5173

volumes:
  frontend_build: